In [2]:
import torch

In [3]:
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
scalar.item()

7

In [6]:
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector

tensor([7, 7])

In [9]:
vector.shape

torch.Size([2])

In [12]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([2, 2])

In [16]:
tensor = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [17]:
tensor.shape

torch.Size([1, 3, 3])

In [18]:
tensor.ndim

3

In [21]:
torch.rand(size=(4,5,2))

tensor([[[0.1331, 0.9892],
         [0.6816, 0.9210],
         [0.3419, 0.6778],
         [0.8811, 0.4047],
         [0.6174, 0.5796]],

        [[0.7465, 0.4545],
         [0.4792, 0.8223],
         [0.3901, 0.6511],
         [0.1404, 0.7688],
         [0.5557, 0.2725]],

        [[0.5422, 0.2515],
         [0.1560, 0.8341],
         [0.7630, 0.7293],
         [0.6755, 0.9746],
         [0.1971, 0.2227]],

        [[0.5101, 0.5889],
         [0.8257, 0.1283],
         [0.1082, 0.0221],
         [0.5861, 0.6175],
         [0.2463, 0.3406]]])

In [24]:
torch.zeros(size = (3, 4))

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [23]:
torch.ones(size = (3, 4))

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
torch.arange(0,10,1)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
torch.zeros_like(tensor)

tensor([[[0, 0, 0],
         [0, 0, 0],
         [0, 0, 0]]])

In [29]:
float_16_tensor = torch.tensor([1.0, 3.5, 6.9],
                                dtype = torch.float16)
float_16_tensor

tensor([1.0000, 3.5000, 6.8984], dtype=torch.float16)

In [31]:
float_16_tensor.device

device(type='cpu')

when error with tensors, check:
</br>
1)data
</br>
2) data type
</br>
3) device

In [33]:
from torch import tensor as ts

In [35]:
ts([1,2,3])*ts([3,4,5])

tensor([ 3,  8, 15])

In [37]:
tensor = ts([1,2,3])

In [38]:
tensor * tensor

tensor([1, 4, 9])

In [39]:
tensor.matmul(tensor)

tensor(14)

In [40]:
tensor.shape

torch.Size([3])

In [42]:
t1 = ts([1,2,3])
t2 = ts([[1],[2],[3]])
t1.shape, t2.shape

(torch.Size([3]), torch.Size([3, 1]))

In [43]:
t1.matmul(t2)

tensor([14])

In [44]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

In [48]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=4) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.3378, 0.6147, 0.7451, 0.6186],
        [4.5928, 1.5825, 0.7206, 0.7607],
        [6.8478, 2.5503, 0.6961, 0.9027]], grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 4])


In [50]:
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
x.argmax()

tensor(9)

In [55]:
x.type(torch.float32).mean()

tensor(45.)

In [63]:
x.view((5,2))

tensor([[ 0, 10],
        [20, 30],
        [40, 50],
        [60, 70],
        [80, 90]])

In [70]:
y = torch.arange(0,1000,100)
y

tensor([  0, 100, 200, 300, 400, 500, 600, 700, 800, 900])

In [71]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [73]:
torch.stack([x,y], dim=1)

tensor([[  0,   0],
        [ 10, 100],
        [ 20, 200],
        [ 30, 300],
        [ 40, 400],
        [ 50, 500],
        [ 60, 600],
        [ 70, 700],
        [ 80, 800],
        [ 90, 900]])

In [78]:
torch.unsqueeze(x, 1)

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [80]:
x.view(10,1)

tensor([[ 0],
        [10],
        [20],
        [30],
        [40],
        [50],
        [60],
        [70],
        [80],
        [90]])

In [81]:
x,x.numpy()

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]),
 array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]))

In [83]:
x.numpy().dtype

dtype('int64')

In [85]:
torch.from_numpy(x.numpy()).type(torch.float32)

tensor([ 0., 10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [87]:
torch.cuda.is_available()

False

In [88]:
x.to('cuda')

AssertionError: Torch not compiled with CUDA enabled